---
- name: infrastructure lb
  hosts: lb
  vars_files:
    - secrets.yml
  roles:
    - role: ssh
    - role: loadbalancer
    - role: webserver

- name: infrastructure db
  hosts: db
  vars_files:
    - secrets.yml
  roles:
    - role: ssh
    - role: database