---
- name: infrastructure lb
  hosts: lb
#  vars_files:
#    - secrets.yml
  roles:
    - role: loadbalancer

- name: infrastructure db
  hosts: db
 #  vars_files:
 #    - secrets.yml
  roles:
    - role: database