---

  sudo: True
  tasks:
    - name: Create new sudo user (admin)
      user: >
        name=kundea
        state=present
        createhome=yes
        groups=sudo

    - name: Set authorized key took from file
      authorized_key:
        user: kundea
        state: present
        key: "{{ lookup('file', '/home/ulinux/.ssh/id_rsa.pub') }}"

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'