---

- name: Create new sudo user (admin)
  sudo: True
  user: >
    name=kundea
    state=present
    createhome=yes
    groups=sudo
    shell=/bin/bash

- name: Set authorized key took from file
  sudo: True
  authorized_key:
    user: kundea
    state: present
    key: "{{ lookup('file', '/home/ulinux/.ssh/id_rsa.pub') }}"

- name: Allow 'sudo' group to have passwordless sudo
  sudo: True
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'